stages:
  prepare-mnist:
    cmd: python3 prepare-mnist.py
    deps:
    - ../../data/fashion-mnist/t10k-images-idx3-ubyte.gz
    - ../../data/fashion-mnist/t10k-labels-idx1-ubyte.gz
    - ../../data/fashion-mnist/train-images-idx3-ubyte.gz
    - ../../data/fashion-mnist/train-labels-idx1-ubyte.gz
    - prepare-mnist.py
    outs:
    - ../../data/fashion-mnist/test.pickle
    - ../../data/fashion-mnist/train.pickle
  train:
    cmd: dvc push && python3 train-wrapper.py
    deps:
    - ../../data/fashion-mnist/test.pickle
    - ../../data/fashion-mnist/train.pickle
    - train-wrapper.py
    outs:
      - trained_model.json
    params:
    - train.n_neighbours
    - train.is_vertex
